# Completion for `cluster`, for bash 3.2 and later, and for zsh through its
# bash completion support:
#
#   bash:  source ~/cluster/completions/cluster.bash
#   zsh:   autoload -U +X compinit && compinit
#          autoload -U +X bashcompinit && bashcompinit
#          source ~/cluster/completions/cluster.bash
#
# Completion is intentionally local-only. Login names come from state files and
# session names come from sessions.cache, which `cluster ls` refreshes wholesale
# and every confirmed create/kill amends as it happens; pressing TAB never
# probes SSH, tmux, or an SSHFS mount.

# >>> generated by `cluster _complete-data --update`; do not edit by hand >>>
_CLUSTER_BACKENDS='fasrc nersc'
_CLUSTER_BACKEND_WORDS='fasrc nersc fas perlmutter'
_CLUSTER_DEFAULT_BACKEND='fasrc'
_CLUSTER_SETTINGS='AUTO_MOUNT BACKEND BOOT_NETWORK_POLL_INTERVAL BOOT_RETRY_DELAY
    BOOT_RETRY_DELAY_MAX BOOT_TRIES BOOT_WAIT BRIDGE_LOGIN BRIDGE_MIN_CERT_LEFT
    BRIDGE_VERIFY_TIMEOUT CERT_RENEW_MARGIN COLLAB COMPANION_ADOPT_HUB_EDITS
    COMPANION_MAX_BYTES COMPANION_SYNC_TIMEOUT CONNECT_TIMEOUT CRED_DIR CRED_ROOT
    CTL_DIR DEFAULT_LOGIN EXTERNAL_SSH_SERVER_ALIVE_COUNT_MAX
    EXTERNAL_SSH_SERVER_ALIVE_INTERVAL FORCE_PORTABLE FOREIGN_OWNER_OPTIONS GLOBUS
    GLOBUS_COLLECTION HOST INTERACTIVE_RETRIES KEY LABEL LAYOUT_INTERVAL LINGER
    LINGER_INTERVAL LINGER_KEEPER LIST_WORKERS LOCK_PATIENCE MACFUSE_BACKEND
    MASTER_READY_WAIT MAX_LOGINS MOUNT_BUSY_GRACE MOUNT_CHECK_TIMEOUT
    MOUNT_FAILBACK_TICKS MOUNT_FAILOVER MOUNT_FAILOVER_AFTER MOUNT_FAILOVER_TRIES
    MOUNT_NODES MOUNT_NODE_MAX_DSTATE MOUNT_ROOT NERSC_NODE_CANDIDATES NEW_LOGIN_MODE
    NODES NODE_HOSTS NODE_PROBE_TIMEOUT NODE_PROBE_TRIES NODE_REACH_SSH_TIMEOUT
    NODE_REACH_TIMEOUT NTP_SERVER ONE_LOGIN_PER_NODE ONE_MOUNT_PER_BACKEND
    PEER_CONNECT_TIMEOUT POOL_OPEN_TRIES RCLONE REAPS_ON_LOGOUT RECONNECT_DELAY
    RECONNECT_DELAY_MAX RECONNECT_HALF_LIFE REFRESH_TRIES REFUSAL_CONFIRM_DELAY
    RELAY_BIN RELAY_HOST RELAY_RETRIES RELAY_RETRY_DELAY RELAY_RETRY_DELAY_MAX
    RELAY_RETRY_HALF_LIFE REMOTE_CHECK_TIMEOUT REMOTE_COMMAND_TIMEOUT REMOTE_RCLONE
    SCOPE SETUP_DRIFT_CHECK_INTERVAL SETUP_REMOTE_TIMEOUT SETUP_SYNC_NERSC_TOOL
    SHARED_TRANSFER_CHECKERS SHARED_TRANSFER_TRANSFERS SSHPROXY_TIMEOUT SSH_CONFIG
    SSH_MAX_SESSIONS SSH_SERVER_ALIVE_COUNT_MAX SSH_SERVER_ALIVE_INTERVAL STATE_ROOT
    STOP_TIMEOUT TOTP_LOCK_PATIENCE TRANSFER_CHECKERS TRANSFER_CONNECTIONS
    TRANSFER_IO_TIMEOUT TRANSFER_MULTI_THREAD_STREAMS TRANSFER_OPEN_TRIES
    TRANSFER_PROBE_TIMEOUT TRANSFER_PROBE_TRIES TRANSFER_RECONNECTS TRANSFER_RETRIES
    TRANSFER_TRANSFERS VSCODE_SETTINGS VSCODE_TAB_TITLE WATCH_BACKOFF_MAX
    WATCH_FAILURE_HALF_LIFE WATCH_INTERVAL WATCH_RETRIES WATCH_START_TIMEOUT WORKSTATION'
_CLUSTER_CREDENTIALS='LOGIN_NAME OTP PASS PASSWORD TOTP TOTP_SEED USER USERNAME'

_cluster_alias() {
    case "$1" in
        fas) printf '%s' fasrc ;;
        perlmutter) printf '%s' nersc ;;
        *) printf '%s' "$1" ;;
    esac
}

_cluster_builtin_nodes() {
    # The login nodes, which NODES replaces.
    case "$1" in
        fasrc) printf '%s\n' holylogin05 holylogin06 holylogin07 holylogin08 boslogin06 \
            boslogin07 boslogin08 ;;
        nersc) printf '%s\n' login01 login02 login03 login04 login05 login06 login07 \
            login08 login09 login10 login11 login12 login13 login14 login15 login16 \
            login17 login18 login19 login20 login21 login22 login23 login24 login25 \
            login26 login27 login28 login29 login30 login31 login32 login33 login34 \
            login35 login36 login37 login38 login39 login40 ;;
    esac
}

_cluster_fixed_nodes() {
    # The other node classes, which NODES leaves alone.
    case "$1" in
        nersc) printf '%s\n' dtn01 dtn02 dtn03 dtn04 ;;
    esac
}
# <<< generated <<<

_cluster_lines_to_reply() {
    # COMPREPLY from stdin, one reply per line, so a filename with a space in
    # it stays one reply (bash 3.2 has no mapfile).
    local line
    COMPREPLY=()
    while IFS= read -r line; do COMPREPLY+=("$line"); done
}

# A TAB starts as few processes as it can, because each one is time the
# terminal waits: the helpers below hand back a word in _cluster_word or
# _cluster_value rather than printing one for a $(...) to catch, and read
# what _cluster_context works out once per TAB rather than once per lookup.

_cluster_recase() {
    # $1 with each letter of $2 changed to the one at the same place in $3,
    # into _cluster_word. In the shell, as bash 3.2 has no ${1,,}; ASCII
    # letters only, which is what backend names are made of.
    local text="$1" from="$2" to="$3" char rest
    _cluster_word=""
    while [ -n "$text" ]; do
        char="${text%"${text#?}"}"
        text="${text#?}"
        case "$from" in
            *"$char"*)
                rest="${from#*"$char"}"
                char="${to:$((${#to} - ${#rest} - 1)):1}" ;;
        esac
        _cluster_word="$_cluster_word$char"
    done
}

_cluster_lower() {
    case "$1" in
        *[[:upper:]]*) _cluster_recase "$1" ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz ;;
        *) _cluster_word="$1" ;;
    esac
}

_cluster_upper() {
    case "$1" in
        *[[:lower:]]*) _cluster_recase "$1" abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ ;;
        *) _cluster_word="$1" ;;
    esac
}

_cluster_env() {
    # The exported variable $1, into _cluster_value, as printenv prints it:
    # the tool only ever sees exported variables. Most of those asked for are
    # not set at all, which the shell can tell without printenv's process.
    # A name is only expanded once it is known to be one; eval is how zsh
    # and bash both do an indirect expansion.
    _cluster_value=""
    case "$1" in
        ""|[!ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*|*[!ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_]*)
            # No shell variable has a name like this, but the environment can.
            _cluster_value="$(printenv "$1")"
            return 0 ;;
    esac
    eval "[ -n \"\${$1+set}\" ]" || return 0
    _cluster_value="$(printenv "$1")"
}

_cluster_xdg() {
    # An XDG base directory, into _cluster_value: the variable when it is an
    # absolute path, else the default, as the tool reads them.
    _cluster_env "$1"
    case "$_cluster_value" in
        /*) ;;
        *) _cluster_value="$2" ;;
    esac
}

_cluster_read_settings() {
    # settings.ini file $1, into _cluster_ini, as _cluster_file_setting looks
    # things up in it: a "\nSECTION\tKEY\tVALUE" entry for each setting, with
    # the key in upper case and only the later value of one given twice. A
    # section or key with a tab in it is left out; nothing looks one up.
    _cluster_ini="$(awk '
        { line=$0; sub(/^[[:space:]]+/, "", line); sub(/[[:space:]]+$/, "", line) }
        substr(line, 1, 1) == "[" && index(line, "]") {
            end=length(line)
            while (substr(line, end, 1) != "]") end--
            current=substr(line, 2, end - 2)
            next
        }
        match(line, /[=:]/) {
            name=substr(line, 1, RSTART - 1); sub(/[[:space:]]+$/, "", name)
            value=substr(line, RSTART + 1); sub(/^[[:space:]]+/, "", value)
            if (!index(current name, "\t")) found[current "\t" toupper(name)]=value
        }
        END { for (entry in found) printf "\n%s\t%s", entry, found[entry] }
    ' "$1")"
}

_cluster_file_setting() {
    # KEY from [SECTION] of settings.ini, into _cluster_value, read as the
    # tool reads it: the section name exactly, the key in any case, and
    # where either is given twice, the later value.
    local nl=$'\n' tab=$'\t' entry rest
    entry="$nl$1$tab$2$tab"
    _cluster_value=""
    case "$1" in *"$tab"*|*"$nl"*) return 0 ;; esac
    case "$_cluster_ini" in
        *"$entry"*)
            rest="${_cluster_ini#*"$entry"}"
            _cluster_value="${rest%%"$nl"*}" ;;
    esac
}

_cluster_is_backend() {
    case " $_CLUSTER_BACKENDS " in *" $1 "*) return 0 ;; esac
    return 1
}

_cluster_profiles() {
    # The backends settings.ini adds, one per line: each section with a TYPE,
    # as clustertool.backends finds them. Named only with --backend.
    _cluster_context || { _cluster_with_context _cluster_profiles; return; }
    local section key value
    while IFS=$'\t' read -r section key value; do
        [ "$key" = TYPE ] && ! _cluster_is_backend "$section" && printf '%s\n' "$section"
    done <<< "$_cluster_ini"
    return 0
}

_cluster_normalize_backend() {
    # $1 as the backend it names, into _cluster_word: in lower case, and an
    # alias as its backend. True when $1 is a backend's name or alias, as
    # --NAME and NAME: accept it; anything else is left as it is.
    _cluster_lower "$1"
    case " $_CLUSTER_BACKEND_WORDS " in *" $_cluster_word "*) ;; *) return 1 ;; esac
    # Every other backend word is a name already, and _cluster_alias would
    # hand it back as it is, from a subshell.
    _cluster_is_backend "$_cluster_word" || _cluster_word="$(_cluster_alias "$_cluster_word")"
    return 0
}

_cluster_named_backend() {
    # The backend this command line actually *names*, or nothing, into
    # _cluster_named.
    #
    # Same rule as cli.main's `explicit`: a --nersc-style flag, a verb prefix,
    # --backend, or CLUSTER_BACKEND. Nothing named means every backend is in
    # scope, which is what makes completion agree with `ls` and `close`.
    local i word
    _cluster_named=""
    for ((i = 1; i < ${#COMP_WORDS[@]}; i++)); do
        word="${COMP_WORDS[i]}"
        case "$word" in
            --backend)
                _cluster_normalize_backend "${COMP_WORDS[i+1]}"
                _cluster_named="$_cluster_word"; return ;;
            --backend=*)
                _cluster_normalize_backend "${word#--backend=}"
                _cluster_named="$_cluster_word"; return ;;
            --*)
                if _cluster_normalize_backend "${word#--}"; then
                    _cluster_named="$_cluster_word"; return
                fi ;;
            *:*)
                # Only a real backend name is a prefix. Any other colon is part
                # of an argument (`cp host:/p`, `strays check NODE:SESSION`)
                # and names no backend.
                _cluster_normalize_backend "${word%%:*}"
                if _cluster_is_backend "$_cluster_word"; then
                    _cluster_named="$_cluster_word"; return
                fi ;;
        esac
    done
    _cluster_env CLUSTER_BACKEND
    [ -z "$_cluster_value" ] || { _cluster_normalize_backend "$_cluster_value"; _cluster_named="$_cluster_word"; }
}

_cluster_with_context() {
    # Run "$@" with a context of its own for _cluster_context to fill. These
    # are local here, which in bash and zsh alike makes them the variables
    # every function it calls reads and sets, and gone once it returns.
    local _cluster_scope=1 _cluster_ready="" _cluster_ini="" _cluster_named="" \
        _cluster_be="" _cluster_BE="" _cluster_root="" _cluster_value="" _cluster_word=""
    "$@"
}

_cluster_context() {
    # Work out what the helpers read, once per TAB: settings.ini
    # (_cluster_ini), the backend the line names (_cluster_named), the one a
    # *new* login and so the node list belongs to (_cluster_be, and as
    # CLUSTER_<BACKEND>_ spells it, with '-' as '_': _cluster_BE), and the
    # state directory
    # (_cluster_root). Returns 1 outside _cluster_with_context, which holds
    # them; a helper called on its own then runs itself inside one.
    local file root
    [ -n "${_cluster_scope-}" ] || return 1
    [ -z "$_cluster_ready" ] || return 0
    _cluster_xdg XDG_CONFIG_HOME "$HOME/.config"
    file="$_cluster_value/cluster/settings.ini"
    if [ -f "$file" ]; then _cluster_read_settings "$file"; fi
    _cluster_named_backend
    _cluster_be="$_cluster_named"
    if [ -z "$_cluster_be" ]; then
        _cluster_file_setting global BACKEND
        _cluster_normalize_backend "$_cluster_value"
        _cluster_be="${_cluster_word:-$_CLUSTER_DEFAULT_BACKEND}"
    fi
    _cluster_upper "$_cluster_be"
    _cluster_BE="${_cluster_word//-/_}"
    # Same three sources, in the same order, as config.global_value("STATE_ROOT"):
    # the environment, then [global] in settings.ini, then the XDG default, so
    # relocated state completes too.
    _cluster_env CLUSTER_STATE_ROOT
    [ -n "$_cluster_value" ] || _cluster_file_setting global STATE_ROOT
    if [ -n "$_cluster_value" ]; then
        # The tool expands a leading ~ in a path setting, so the same value
        # must find the same directory here.
        root="$_cluster_value"
        case "$root" in
            "~") root="$HOME" ;;
            "~/"*) root="$HOME/${root#"~/"}" ;;
        esac
        _cluster_root="${root%/}"
    else
        _cluster_xdg XDG_STATE_HOME "$HOME/.local/state"
        _cluster_root="$_cluster_value/cluster"
    fi
    _cluster_ready=1
}

_cluster_in_scope() {
    # "$@" DIR for the state directory of each backend in scope: the one
    # this line names, or every one with state here. The same rule as
    # `ctx.scope()`: naming a backend narrows the command to it.
    local dir
    if [ -n "$_cluster_named" ]; then
        "$@" "$_cluster_root/$_cluster_named"
    else
        for dir in "$_cluster_root"/*/; do
            [ -d "$dir" ] && "$@" "${dir%/}"
        done
    fi
    return 0
}

_cluster_add_file() {
    # NAME DIR: DIR/NAME onto _cluster_files when it is a file, for one awk
    # to read them all.
    [ -f "$2/$1" ] && _cluster_files+=("$2/$1")
    return 0
}

_cluster_logins_in() {
    # The logins with state in directory $1.
    local file name
    for file in "$1"/*.node "$1"/*.json; do
        [ -e "$file" ] || continue
        name="${file##*/}"
        printf '%s\n' "${name%.*}"
    done
}

_cluster_logins() {
    # A name that lives on another backend is refused by `ctx.login()`, so
    # offering it under an explicit --nersc is offering an error.
    _cluster_context || { _cluster_with_context _cluster_logins; return; }
    _cluster_in_scope _cluster_logins_in | sort -u
}

_cluster_sessions() {
    _cluster_context || { _cluster_with_context _cluster_sessions "$@"; return; }
    local login="$1" file
    local -a _cluster_files=()
    [ -n "$login" ] || return
    for file in "$_cluster_root"/*/sessions.cache; do
        [ -f "$file" ] && _cluster_files+=("$file")
    done
    ((${#_cluster_files[@]})) || return 0
    awk -F '\t' -v login="$login" '$1 == login && $2 != "" { print $2 }' \
        "${_cluster_files[@]}" | sort -u
}

_cluster_all_sessions() {
    _cluster_context || { _cluster_with_context _cluster_all_sessions; return; }
    local file
    local -a _cluster_files=()
    for file in "$_cluster_root"/*/sessions.cache; do
        [ -f "$file" ] && _cluster_files+=("$file")
    done
    ((${#_cluster_files[@]})) || return 0
    awk -F '\t' '$2 != "" { print $2 }' "${_cluster_files[@]}" | sort -u
}

_cluster_stray_sessions() {
    # Session names recorded as left behind, from abandoned.tsv
    # (node, session, former owner). This is the one stray source that is
    # local: the other is the breadcrumb catalogue in the cluster home, and
    # reading that would mean a connection.
    #
    # With a node, only that node's; without, all of them.
    _cluster_context || { _cluster_with_context _cluster_stray_sessions "$@"; return; }
    local node="$1"
    local -a _cluster_files=()
    _cluster_in_scope _cluster_add_file abandoned.tsv
    ((${#_cluster_files[@]})) || return 0
    awk -F '\t' -v node="$node" \
        '$1 != "" && $2 != "" && (node == "" || $1 == node) { print $2 }' \
        "${_cluster_files[@]}" | sort -u
}

_cluster_stray_targets() {
    # A stray target is a node, a session name, or NODE:SESSION. Every node of
    # the backend is offered because a stray sits, by definition, where no
    # login is — so local state names no node to narrow to.
    _cluster_context || { _cluster_with_context _cluster_stray_targets; return; }
    _cluster_nodes
    _cluster_stray_sessions ""
}

_cluster_setting() {
    # A per-backend setting, into _cluster_value, resolved in config.Settings'
    # order: CLUSTER_<BACKEND>_KEY, CLUSTER_KEY, then [backend] and [global]
    # in settings.ini. Empty when none of them sets it.
    _cluster_env "CLUSTER_${_cluster_BE}_$1"
    [ -n "$_cluster_value" ] || _cluster_env "CLUSTER_$1"
    [ -n "$_cluster_value" ] || _cluster_file_setting "$_cluster_be" "$1"
    [ -n "$_cluster_value" ] || _cluster_file_setting global "$1"
}

_cluster_default_login() {
    _cluster_context || { _cluster_with_context _cluster_default_login; return; }
    _cluster_setting DEFAULT_LOGIN
    printf '%s' "${_cluster_value:-main}"
}

_cluster_nodes() {
    # NODES replaces the built-in login-node list, as it does for the tool
    # itself; the backend's other node classes are always offered.
    _cluster_context || { _cluster_with_context _cluster_nodes; return; }
    local node
    _cluster_setting NODES
    if [ -n "$_cluster_value" ]; then
        for node in $_cluster_value; do printf '%s\n' "${node%%.*}"; done
    elif _cluster_is_backend "$_cluster_be"; then
        _cluster_builtin_nodes "$_cluster_be"
    else
        # An ssh backend's nodes are the ones NODE_HOSTS says how to reach.
        _cluster_setting NODE_HOSTS
        for node in $_cluster_value; do printf '%s\n' "${node%%=*}"; done
    fi
    _cluster_fixed_nodes "$_cluster_be"
}

#: Every command and alias, which a TAB before the verb offers.
_CLUSTER_COMMAND_NAMES='a attach auth backends boot bridge cert cfg ch channels clean close config
    copy cp doctor fixterm forget init k kill-session l linger list login logout ls m monitor
    mount mounts move n new new-session new-window nersc-tool node nodes nt open pin pins pull
    push r reconnect refresh rename repair repin rescue reset-state restore setup
    restore-layout run send session sessions sh shell ss ssh ssh-command st status stray
    strays task tmux tmux-list transfer umount unmount unpin unwatch w watch where window xfer'

_cluster_command_names() {
    local name
    for name in $_CLUSTER_COMMAND_NAMES; do printf '%s\n' "$name"; done
}

_cluster_options() {
    case "$1" in
        auth|cert) printf '%s\n' --force --drop --status ;;
        bridge) printf '%s\n' --force --cron --no-verify --overwrite-tool ;;
        nersc-tool|nt) printf '%s\n' --force --tool-only --no-verify ;;
        setup) printf '%s\n' --check --local-only --remote-only --no-tool ;;
        list|ls) printf '%s\n' -q --quiet ;;
        linger) printf '%s\n' -q --quiet --remove-keeper --install-hook ;;
        strays|stray) printf '%s\n' -y --yes --as ;;
        channels|ch) printf '%s\n' --free ;;
        backends) printf '%s\n' --type --label ;;
        login|l|open|shell|sh|ssh) printf '%s\n' --no-mount ;;
        attach|a|tmux) printf '%s\n' --here --no-mount ;;
        new|n|new-session|task|session)
            printf '%s\n' -d --detach --here --no-mount -c --cwd ;;
        close|logout) printf '%s\n' --keep-tmux --abandon-tmux --all ;;
        repair) printf '%s\n' --attempt ;;
        boot) printf '%s\n' --wait --tries ;;
        ssh-command) printf '%s\n' --transfer --node --quiet --rclone ;;
        forget|reset-state) printf '%s\n' --all-backends -n --dry-run -y --yes ;;
        rename) printf '%s\n' --force ;;
        clean)
            printf '%s\n' --all --all-backends --dry-run --include-untagged --force -y --yes ;;
        transfer|xfer|copy|cp)
            printf '%s\n' --via --node --engine --executor --peer-node \
                --no-agent-forward --keep --close --force --contents --up --down \
                --move --sync -n --dry-run -q --quiet -P --progress -L -l \
                --skip-symlinks --transfers --checkers -y --yes ;;
        refresh|reconnect) printf '%s\n' --keep-tmux ;;
        repin|move|unpin) printf '%s\n' --migrate --abandon -y --yes ;;
        config|cfg) printf '%s\n' --all --global ;;
    esac
}

_cluster_match() {
    # PREFIX FRAGMENT WORDS: PREFIX and each of the space-separated WORDS that
    # starts with FRAGMENT, one per line, as `compgen -P PREFIX -W WORDS --
    # FRAGMENT` prints them but with every word taken as it is. compgen -W
    # expands its words, so a session named $(...) on a cluster would run
    # here on a TAB; splitting by hand also leaves globbing alone.
    local prefix="$1" fragment="$2" rest="$3" word
    while :; do
        rest="${rest#"${rest%%[![:space:]]*}"}"
        [ -n "$rest" ] || return 0
        word="${rest%%[[:space:]]*}"
        rest="${rest#"$word"}"
        case "$word" in "$fragment"*) printf '%s%s\n' "$prefix" "$word" ;; esac
    done
}

_cluster_reply_words() {
    _cluster_lines_to_reply < <(_cluster_match "" "$cur" "$1")
}

_cluster_reply_files() {
    # Filenames, with the words in $1 beside them. `-o filenames` quotes a
    # space where the shell supports asking for it (bash 4 and later).
    if type compopt >/dev/null 2>&1; then compopt -o filenames 2>/dev/null; fi
    _cluster_lines_to_reply < <(_cluster_match "" "$cur" "${1-}"; compgen -f -- "$cur")
}

#: The part of the current word readline keeps; see _cluster_ltrim.
_cluster_prefix=""

_cluster_break_prefix() {
    # Everything up to and including the last COMP_WORDBREAKS character in a
    # word, into _cluster_prefix. Readline replaces only what *follows* that
    # character, so this is the part of the word that stays on the line
    # whatever we answer.
    local word="$1" char candidate
    _cluster_prefix=""
    for char in : =; do
        case "${COMP_WORDBREAKS:-}" in *"$char"*) ;; *) continue ;; esac
        case "$word" in *"$char"*) ;; *) continue ;; esac
        candidate="${word%"${word##*"$char"}"}"
        ((${#candidate} > ${#_cluster_prefix})) && _cluster_prefix="$candidate"
    done
    return 0
}

_cluster_rejoin() {
    # Put back the words bash tore apart.
    #
    # COMP_WORDS is split at COMP_WORDBREAKS, which holds ':' and '=', so a
    # real terminal hands this function <nersc><:><ls> where a caller that
    # builds the array itself hands it <nersc:ls>. Every case below reasons
    # about whole tokens, so rebuild them from the line the shell typed — and
    # only then, because a caller that passed no COMP_LINE is not readline and
    # wants whole tokens back. zsh hands over whole words already.
    _cluster_prefix=""
    [ -n "${COMP_LINE+set}" ] || return 0
    [ -z "${ZSH_VERSION-}" ] || return 0
    local IFS=$' \t\n' head
    local -a words=() before=()
    head="${COMP_LINE:0:$COMP_POINT}"
    read -r -a words <<< "$COMP_LINE"
    read -r -a before <<< "$head"
    COMP_WORDS=("${words[@]}")
    COMP_CWORD=${#before[@]}
    case "$head" in
        ""|*[[:space:]]) ;;
        *) COMP_CWORD=$((COMP_CWORD - 1)) ;;
    esac
    _cluster_break_prefix "${COMP_WORDS[COMP_CWORD]}"
    return 0
}

_cluster_ltrim() {
    # A match carrying the whole "nersc:ls" token would be inserted after the
    # colon that is already on the line, making "nersc:nersc:ls". Hand back
    # only the fragment readline is going to replace.
    local i word
    local -a keep=()
    [ -n "$_cluster_prefix" ] || return 0
    for ((i = 0; i < ${#COMPREPLY[@]}; i++)); do
        word="${COMPREPLY[i]#"$_cluster_prefix"}"
        [ -n "$word" ] && keep+=("$word")
    done
    COMPREPLY=("${keep[@]}")
}

_cluster() {
    # Under zsh's bashcompinit, ksh emulation gives this call bash's 0-based
    # arrays and word splitting; the options come back when it returns.
    [ -z "${ZSH_VERSION-}" ] || emulate -L ksh
    _cluster_rejoin
    _cluster_with_context _cluster_complete
    _cluster_ltrim
}

_cluster_complete() {
    local cur prev i word verb="" verb_index=0 skip=0 remote=0 remote_words=0
    local -a positional=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ "$cur" == --backend=* ]]; then
        _cluster_context
        _cluster_lines_to_reply < <(
            _cluster_match "${cur%%=*}=" "${cur#*=}" \
                "$_CLUSTER_BACKEND_WORDS $(_cluster_profiles)")
        return
    fi

    case "$prev" in
        --backend)
            _cluster_context
            _cluster_reply_words "$_CLUSTER_BACKEND_WORDS $(_cluster_profiles)"
            return ;;
        --via|--login)
            _cluster_context
            _cluster_reply_words "$(_cluster_logins)"
            return ;;
        --node|--peer-node)
            _cluster_context
            _cluster_reply_words "$(_cluster_nodes)"
            return ;;
        --engine)
            _cluster_reply_words "auto direct relay globus"
            return ;;
        --executor)
            _cluster_context
            _cluster_reply_words "$_CLUSTER_BACKENDS $(_cluster_profiles)"
            return ;;
        --cwd|-c)
            _cluster_lines_to_reply < <(compgen -d -- "$cur")
            return ;;
        --as|--wait|--tries|--attempt|--transfers|--checkers)
            # `strays adopt --as NAME` names a login that does not exist yet,
            # so the existing ones are the wrong answer, as they are for the
            # new-session slot. The rest take a number.
            COMPREPLY=()
            return ;;
    esac

    # Find the verb, skipping global flags and their values.
    for ((i = 1; i < COMP_CWORD; i++)); do
        word="${COMP_WORDS[i]}"
        if ((skip)); then skip=0; continue; fi
        case "$word" in
            --backend) skip=1 ;;
            -*) ;;
            *) verb="${word#*:}"; verb_index=$i; break ;;
        esac
    done

    local bflags=""
    for word in $_CLUSTER_BACKEND_WORDS; do bflags="$bflags --$word"; done
    if [ -z "$verb" ]; then
        if [[ "$cur" == *:* ]]; then
            local command_backend="${cur%%:*}" command_fragment="${cur#*:}"
            _cluster_normalize_backend "$command_backend"
            if _cluster_is_backend "$_cluster_word"; then
                _cluster_lines_to_reply < <(
                    _cluster_match "$command_backend:" "$command_fragment" \
                        "$_CLUSTER_COMMAND_NAMES")
                return
            fi
        fi
        _cluster_reply_words "$_CLUSTER_COMMAND_NAMES $bflags --backend --help"
        return
    fi

    # Collect completed positional arguments. This keeps completion correct
    # when options precede names (for example: cluster a --here main TAB).
    skip=0
    for ((i = verb_index + 1; i < COMP_CWORD; i++)); do
        word="${COMP_WORDS[i]}"
        if ((skip)); then skip=0; continue; fi
        if ((remote)); then remote_words=$((remote_words + 1)); continue; fi
        case "$word" in
            --) remote=1 ;;
            --backend|--via|--node|--peer-node|--engine|--executor|--cwd|-c|\
            --as|--wait|--tries|--attempt|--transfers|--checkers|--type|--label)
                skip=1 ;;
            -*) ;;
            *) positional+=("$word") ;;
        esac
    done

    if ((remote)); then
        if ((remote_words == 0)); then
            _cluster_lines_to_reply < <(compgen -c -- "$cur")
        else
            _cluster_reply_files
        fi
        return
    fi

    if [[ "$cur" == -* ]]; then
        # --help last: every command answers it, including the ones that parse
        # no options of their own.
        _cluster_reply_words "$(_cluster_options "$verb") $bflags --backend --help"
        return
    fi

    local argno=$(( ${#positional[@]} + 1 ))
    local selected="${positional[0]-}"
    # Worked out here, in this shell, so the $(...) below share it rather
    # than each working it out again; so too for --via and --node above.
    _cluster_context

    case "$verb" in
        config|cfg)
            if ((argno == 1)); then
                _cluster_reply_words "show list get set unset path credentials"
            elif ((argno == 2)); then
                case "${positional[0]}" in
                    get|set|unset)
                        _cluster_reply_words "$_CLUSTER_SETTINGS $_CLUSTER_CREDENTIALS" ;;
                esac
            fi ;;
        backends)
            if ((argno == 1)); then
                _cluster_reply_words "add remove"
            elif ((argno == 2)) && [ "${positional[0]}" = remove ]; then
                _cluster_reply_words "$(_cluster_profiles)"
            fi ;;
        bridge)
            # Both verbs take the hub login to work through.
            if ((argno == 1)); then
                _cluster_reply_words "push status"
            elif ((argno == 2)); then
                _cluster_reply_words "$(_cluster_logins)"
            fi ;;
        nersc-tool|nt)
            if ((argno == 1)); then
                _cluster_reply_words "path install-local install sync"
            elif ((argno == 2)); then
                case "${positional[0]}" in
                    install|sync) _cluster_reply_words "$(_cluster_logins)" ;;
                esac
            fi ;;
        setup)
            ((argno == 1)) && _cluster_reply_words "$(_cluster_logins)" ;;
        strays|stray)
            # Verbs first, then targets. Both come from this machine: a stray is
            # by definition on a node nothing is connected to, so asking the
            # cluster to name them would be the one thing completion must never
            # do.
            #
            # The verb is optional (a bare `cluster strays` lists), so slot one
            # offers verbs *and* targets; slot two is the target for every verb
            # including rename, whose second word is a new name and so has no
            # answer here.
            local stray_verbs="list check adopt rename clear kill"
            if [[ "$cur" == *:* ]]; then
                # NODE:SESSION. Same shape as the `nersc:ls` prefix above; the
                # colon is a word break, which _cluster_ltrim settles.
                local stray_node="${cur%%:*}" stray_fragment="${cur#*:}"
                _cluster_lines_to_reply < <(
                    _cluster_match "$stray_node:" "$stray_fragment" \
                        "$(_cluster_stray_sessions "$stray_node")")
            elif ((argno == 1)); then
                _cluster_reply_words "$stray_verbs $(_cluster_stray_targets)"
            elif ((argno == 2)) && [[ " $stray_verbs " == *" ${positional[0]} "* ]]; then
                _cluster_reply_words "$(_cluster_stray_targets)"
            fi ;;
        attach|a|tmux)
            if ((argno == 1)); then
                _cluster_reply_words "$(_cluster_logins)"
            elif ((argno == 2)); then
                _cluster_reply_words "$(_cluster_sessions "$selected")"
            fi ;;
        new|n|new-session|task|session)
            # The first slot is an existing-or-new login. The second is a new
            # session name, so suggesting existing sessions there is actively
            # misleading (attach/kill are the verbs for existing names).
            ((argno == 1)) && _cluster_reply_words "$(_cluster_logins)" ;;
        kill-session|k)
            if ((argno == 1)); then
                _cluster_reply_words "$(_cluster_logins)"
            elif ((argno == 2)); then
                _cluster_reply_words "$(_cluster_sessions "$selected")"
            fi ;;
        window|new-window|send)
            if ((argno == 1)); then
                _cluster_reply_words \
                    "$(_cluster_logins) $(_cluster_sessions "$(_cluster_default_login)")"
            elif ((argno == 2)); then
                local nl=$'\n'
                case "$nl$(_cluster_logins)$nl" in
                    *"$nl$selected$nl"*) _cluster_reply_words "$(_cluster_sessions "$selected")" ;;
                esac
            fi ;;
        rescue)
            if ((argno == 1)); then
                _cluster_reply_words "$(_cluster_nodes)"
            elif ((argno == 2)); then
                _cluster_reply_words "$(_cluster_all_sessions)"
            fi ;;
        restore-layout|restore)
            if ((argno == 1)); then
                _cluster_reply_words "$(_cluster_logins) $(_cluster_nodes)"
            elif ((argno == 2)); then
                _cluster_reply_words "$(_cluster_nodes)"
            fi ;;
        repin|move)
            if ((argno == 1)); then
                _cluster_reply_words "$(_cluster_logins) $(_cluster_nodes)"
            elif ((argno == 2)); then
                _cluster_reply_words "$(_cluster_nodes)"
            fi ;;
        rename)
            ((argno == 1)) && _cluster_reply_words "$(_cluster_logins)" ;;
        push|pull)
            _cluster_reply_files "$(_cluster_logins)" ;;
        transfer|xfer|copy|cp)
            local prefixes="" backend
            for backend in $_CLUSTER_BACKENDS; do prefixes="$prefixes $backend:"; done
            _cluster_reply_files "$prefixes" ;;
        list|ls|auth|cert|clean)
            _cluster_reply_words "$(_cluster_options "$verb")" ;;
        nodes|mounts|status|st|doctor|fixterm|init)
            COMPREPLY=() ;;
        mount|m)
            if ((argno == 1)); then
                _cluster_reply_words "$(_cluster_logins)"
            elif ((argno == 3)); then
                _cluster_lines_to_reply < <(compgen -d -- "$cur")
            fi ;;
        forget|reset-state|close|logout|login|l|open|where|w|node|channels|ch|\
        run|r|shell|sh|ssh|sessions|ss|tmux-list|umount|unmount|repair|watch|\
        unwatch|monitor|boot|ssh-command|refresh|reconnect|pin|pins|unpin)
            _cluster_reply_words "$(_cluster_logins)" ;;
        *)
            COMPREPLY=() ;;
    esac
}

complete -F _cluster cluster
